"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# My imports
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Render define RENDER=true no deploy — produção usa só o painel, nunca backend/.env
ON_RENDER = os.environ.get('RENDER', '').lower() == 'true'
if not ON_RENDER:
    load_dotenv(BASE_DIR / '.env', override=True)

_DEV_CORS = (
    'http://localhost:3000,http://localhost:5173,'
    'http://127.0.0.1:3000,http://127.0.0.1:5173'
)


def _normalize_origin(value: str) -> str:
    """Corrige typos comuns em URLs de origem (ex.: http// → http://)."""
    origin = value.strip().rstrip('/')
    if origin.startswith('http//'):
        origin = f'http://{origin[6:]}'
    return origin


def _split_env_list(name: str, default: str = '') -> list[str]:
    raw = os.environ.get(name, default)
    seen: set[str] = set()
    result: list[str] = []
    for item in raw.split(','):
        normalized = _normalize_origin(item)
        if normalized and normalized not in seen:
            seen.add(normalized)
            result.append(normalized)
    return result


def _csrf_from_cors_and_hosts(cors_origins: list[str], hosts: list[str]) -> list[str]:
    """Monta CSRF_TRUSTED_ORIGINS a partir de CORS + hosts HTTPS do backend."""
    trusted: set[str] = set(cors_origins)
    for host in hosts:
        if host in ('localhost', '127.0.0.1'):
            continue
        trusted.add(f'https://{host}')
    return list(trusted)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
chave_padrao = 'django-insecure-*d9&dmgyep_six0*ae0din#+$pabf33@b^mr6k3u$@$a-loy^)'
SECRET_KEY = os.environ.get('SECRET_KEY', chave_padrao)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# ALLOWED_HOSTS — local: env + localhost; Render: só o que está no painel
_allowed_hosts_env = _split_env_list('ALLOWED_HOSTS')
_local_hosts = ['localhost', '127.0.0.1']
if ON_RENDER:
    ALLOWED_HOSTS = _allowed_hosts_env
else:
    ALLOWED_HOSTS = list(dict.fromkeys(_allowed_hosts_env + _local_hosts))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party
    'ninja',
    'corsheaders',
    'ninja_jwt',
    
    # Nossos apps
    'api',
    'gestao_freelas',
    'usuarios',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Meu middleware do whitenoise
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # CORS precisa vir antes do CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',
    # Django padrao
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Database alterado

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL')
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configurações para ficheiros de media (Uploads dos utilizadores)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Não se esqueça de avisar o Django de que este é o modelo oficial de utilizador!
AUTH_USER_MODEL = 'usuarios.Usuario'

# Redireciona para a página inicial após o login (vamos criar essa página depois)
LOGIN_REDIRECT_URL = '/' 

# Diz ao Django qual é o nome da rota de login caso um usuário deslogado tente acessar uma página bloqueada
LOGIN_URL = 'login'

# CORS — em produção (Render) só variáveis do painel; local usa defaults de dev
if ON_RENDER:
    CORS_ALLOWED_ORIGINS = _split_env_list('CORS_ALLOWED_ORIGINS')
    CSRF_TRUSTED_ORIGINS = _split_env_list('CSRF_TRUSTED_ORIGINS')
    if not CSRF_TRUSTED_ORIGINS and CORS_ALLOWED_ORIGINS:
        CSRF_TRUSTED_ORIGINS = _csrf_from_cors_and_hosts(CORS_ALLOWED_ORIGINS, _allowed_hosts_env)
else:
    CORS_ALLOWED_ORIGINS = _split_env_list('CORS_ALLOWED_ORIGINS', _DEV_CORS)
    CSRF_TRUSTED_ORIGINS = _split_env_list('CSRF_TRUSTED_ORIGINS', _DEV_CORS)

CORS_ALLOW_CREDENTIALS = True

# Django Ninja JWT Settings
from datetime import timedelta

NINJA_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Validação no Render: deploy falha cedo se o painel estiver incompleto
if ON_RENDER:
    _render_required = []
    if not os.environ.get('DATABASE_URL'):
        _render_required.append('DATABASE_URL')
    if not os.environ.get('SECRET_KEY') or SECRET_KEY == chave_padrao:
        _render_required.append('SECRET_KEY (chave forte no painel Render)')
    if not _allowed_hosts_env:
        _render_required.append('ALLOWED_HOSTS (ex.: seu-app.onrender.com)')
    if not CORS_ALLOWED_ORIGINS:
        _render_required.append('CORS_ALLOWED_ORIGINS (URL do Vercel)')
    if not CSRF_TRUSTED_ORIGINS:
        _render_required.append(
            'CSRF_TRUSTED_ORIGINS ou CORS_ALLOWED_ORIGINS (para derivar CSRF automaticamente)'
        )
    if DEBUG:
        _render_required.append('DEBUG=False')
    if _render_required:
        raise ImproperlyConfigured(
            'Variáveis obrigatórias no painel Render: ' + ', '.join(_render_required)
        )

# Security Settings for Production
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True' if ON_RENDER else 'False') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
