# Generated by Django 6.0.3 on 2026-03-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_freelas', '0003_remove_cliente_email_telefone_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('MENSAL', 'Mensalidade'), ('QUINZENA', 'Quinzena'), ('QUINZENAL', 'Quinzenal'), ('AVULSO', 'Pagamento Avulso / Extra')], default='MENSAL', max_length=10),
        ),
    ]
