# Generated by Django 6.0.3 on 2026-03-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_freelas', '0004_alter_pagamento_tipo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('MENSAL', 'Mensalidade'), ('QUINZENAL', 'Quinzenal'), ('AVULSO', 'Pagamento Avulso / Extra')], default='MENSAL', max_length=10),
        ),
    ]
