# Generated by Django 6.0.3 on 2026-03-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_freelas', '0005_alter_pagamento_tipo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
