# Generated by Django 6.0.3 on 2026-05-23 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_freelas', '0008_pagamento_data_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_entrega',
            field=models.DateField(blank=True, help_text='Data limite para entrega do projeto', null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='progresso',
            field=models.PositiveSmallIntegerField(default=0, help_text='Progresso estimado de entrega (0 a 100)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('DISCOVERY', 'In Discovery'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'Review'), ('COMPLETED', 'Completed')], default='DISCOVERY', help_text='Etapa atual do projeto no quadro Kanban', max_length=20),
        ),
        migrations.AddField(
            model_name='projeto',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total do contrato/projeto', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ProjetoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recorrencia', models.CharField(choices=[('MENSAL', 'Mensal'), ('QUINZENAL', 'Quinzenal'), ('AVULSO', 'Sem Recorrência / Avulso')], default='AVULSO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projeto_ativo', to='gestao_freelas.projeto')),
            ],
        ),
    ]
