# Generated by Django 6.0.3 on 2026-05-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_freelas', '0013_integrity_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projetoativo',
            options={'verbose_name': 'ProjetoAtivo (DEPRECATED)', 'verbose_name_plural': 'ProjetosAtivos (DEPRECATED)'},
        ),
    ]
