# Generated by Django 6.0.3 on 2026-05-23 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_freelas', '0014_alter_projetoativo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjetoAtivo',
        ),
    ]
