# Generated by Django 6.0.3 on 2026-05-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_freelas', '0015_delete_projetoativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='comprovante_bytes',
            field=models.BinaryField(blank=True, help_text='Bytes do comprovante de pagamento', null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='comprovante_mime',
            field=models.CharField(blank=True, help_text='MIME type do comprovante', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='ferramentas',
            field=models.CharField(blank=True, help_text='Ferramentas utilizadas', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='github_repo',
            field=models.URLField(blank=True, help_text='Repositório do projeto no GitHub', null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='imagem_bytes',
            field=models.BinaryField(blank=True, help_text='Dados binários da imagem', null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='imagem_mime',
            field=models.CharField(blank=True, help_text='Tipo MIME da imagem', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=250, null=True),
        ),
    ]
