# Generated by Django 6.0.3 on 2026-05-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_freelas', '0016_pagamento_comprovante_bytes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante_mime',
            field=models.CharField(blank=True, help_text='Tipo MIME do comprovante', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('MENSAL', 'Mensalidade'), ('AVULSO', 'Pagamento Avulso / Extra')], default='MENSAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo_recorrencia',
            field=models.CharField(choices=[('MENSAL', 'Mensal'), ('AVULSO', 'Sem Recorrência / Avulso')], default='AVULSO', help_text='Tipo de recorrência do projeto', max_length=20),
        ),
    ]
