# Generated by Django 6.0.3 on 2026-05-25 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_freelas', '0017_alter_pagamento_comprovante_mime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(blank=True, default='Não informada', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='projeto',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado_em__isnull', True)), fields=('cliente', 'servico'), name='uniq_projeto_cliente_servico_ativo'),
        ),
    ]
